name: writing
favicon: null
layout_spectrum: 0
typography_spectrum: 0.47561
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ffffff'
    - '#ffffff'
    - '#ffffff'
    - '#ffffff'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose:
  - name: shares
    item: null
    url: null
